siva:
  service:
    service-host: http://siva.localhost:8080
server:
  port: 9000
  compression:
    enabled: true
  session:
    cookie:
      http-only: false
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
      enabled: true
  cache:
    caffeine:
      spec: maximumSize=100,expireAfterAccess=20s
management:
  health:
    diskspace:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health
      base-path: /monitoring
  endpoint:
    health:
      show-details: "ALWAYS"

wro4j:
  filterUrl: /owr
  #  cacheName: owr
  managerFactory:
    preProcessors: removeSourceMaps, cssUrlRewriting, cssImport, cssMinJawr, semicolonAppender
